openapi: 3.0.3
info:
  title: Todolist API
  description: The APi for our todolist
  version: 1.0.0
servers:
  - url: htt://localhost:3000
tags:
  - name: tasks
    description: Everything about Tasks
  - name: users
    description: Everything about Users
paths:
  /tasks:
    get:
      tags:
        - tasks
      summary: Toutes les tâches
      description: Retourne toutes les tâches de l'ensemble des utilisateurs
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        label:
          type: string
          example: Coder une API REST avec nodeJs et Express
        done:
          type: boolean
          example: true
        userId:
          type: integer
          format: int64
          example: 1